name: Latest YouTube Videos
on:
  schedule:
    # Runs every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBELATEST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCE9ODjNIkOHrnSdkYWLfYhg"
          custom_tags: "videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          max_post_count: 5
          template: '
            <tr>
              <td>
                <a href="$url">
                  <img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg">
                </a>
              </td>
              <td width="231px">
                <a href="$url">$title</a>
                <br/>$date
              </td>
            </tr>'
          committer_email: "yauhen.kavalchuk@gmail.com"
